#!/usr/bin/env python3
"""
build.py — ShortTechBible build system
- Parses all entries/*.md
- Generates dist/acronyms.json and dist/acronyms.csv
- Generates docs/acronyms_data.js for the GitHub Pages search interface
- Updates README.md counters and Acronym of the Day section
"""

import re
import sys
import json
import csv
from pathlib import Path
from datetime import datetime, timezone
from collections import defaultdict

# ── Paths ────────────────────────────────────────────────────────────────────

ROOT        = Path(__file__).parent.parent
ENTRIES_DIR = ROOT / "entries"
DIST_DIR    = ROOT / "dist"
DOCS_DIR    = ROOT / "docs"
README_PATH = ROOT / "README.md"
OUTPUT_JSON = DIST_DIR / "acronyms.json"
OUTPUT_CSV  = DIST_DIR / "acronyms.csv"
OUTPUT_JS   = DOCS_DIR / "acronyms_data.js"

# ── Parsing (shared logic with validate.py) ───────────────────────────────────

ENTRY_SEPARATOR = re.compile(r"^---\s*$", re.MULTILINE)
HEADER_RE       = re.compile(r"^## ([A-Z0-9]+)(?:\s+—\s+(.+))?$")
DIFFICULTY_RE   = re.compile(r"^\*\*Difficulty:\*\*\s+(.+)$")
CATEGORY_RE     = re.compile(r"^\*\*Category:\*\*\s+(.+)$")


def parse_entries_from_file(filepath: Path) -> list[dict]:
    text = filepath.read_text(encoding="utf-8")
    raw_blocks = ENTRY_SEPARATOR.split(text)
    entries = []

    for block in raw_blocks:
        lines = block.strip().splitlines()
        if not lines:
            continue

        entry = {
            "acronym":   None,
            "full_name": None,
            "description": "",
            "difficulty": None,
            "category":  None,
            "letter":    filepath.stem.upper(),
        }

        i = 0
        while i < len(lines) and not lines[i].strip():
            i += 1

        if i < len(lines):
            m = HEADER_RE.match(lines[i].strip())
            if m:
                entry["acronym"]   = m.group(1)
                entry["full_name"] = m.group(2) or ""
            i += 1

        if entry["acronym"] is None:
            continue

        desc_lines = []
        in_desc = True
        while i < len(lines):
            stripped = lines[i].strip()
            dm = DIFFICULTY_RE.match(stripped)
            cm = CATEGORY_RE.match(stripped)
            if dm:
                entry["difficulty"] = dm.group(1).strip()
                in_desc = False
            elif cm:
                entry["category"] = cm.group(1).strip()
                in_desc = False
            elif in_desc and stripped:
                desc_lines.append(stripped)
            i += 1

        entry["description"] = " ".join(desc_lines)
        entries.append(entry)

    return entries


def load_all_entries() -> list[dict]:
    all_entries = []
    for md_file in sorted(ENTRIES_DIR.glob("*.md")):
        entries = parse_entries_from_file(md_file)
        all_entries.extend(entries)
    return all_entries


# ── Acronym of the Day ────────────────────────────────────────────────────────

def get_acronym_of_the_day(entries: list[dict]) -> dict:
    """Deterministic selection based on day of year, cycles through all entries."""
    if not entries:
        return {}
    day_of_year = datetime.now(timezone.utc).timetuple().tm_yday
    return entries[day_of_year % len(entries)]


# ── Dist generation ───────────────────────────────────────────────────────────

def generate_json(entries: list[dict]) -> None:
    DIST_DIR.mkdir(exist_ok=True)
    data = {
        "meta": {
            "total":        len(entries),
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source":       "https://github.com/FabioXY/ShortTechBible",
        },
        "entries": entries,
    }
    OUTPUT_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  ✓ Generated {OUTPUT_JSON.relative_to(ROOT)}")


def generate_csv(entries: list[dict]) -> None:
    DIST_DIR.mkdir(exist_ok=True)
    fieldnames = ["acronym", "full_name", "description", "difficulty", "category", "letter"]
    with OUTPUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(entries)
    print(f"  ✓ Generated {OUTPUT_CSV.relative_to(ROOT)}")


def generate_js_for_docs(entries: list[dict]) -> None:
    """Write a JS file that the GitHub Pages site imports directly (no CORS issues)."""
    DOCS_DIR.mkdir(exist_ok=True)
    js_data    = json.dumps(entries, ensure_ascii=False, indent=2)
    js_content = f"// Auto-generated by build.py — do not edit manually\nconst ACRONYMS_DATA = {js_data};\n"
    OUTPUT_JS.write_text(js_content, encoding="utf-8")
    print(f"  ✓ Generated {OUTPUT_JS.relative_to(ROOT)}")


# ── README update ─────────────────────────────────────────────────────────────

COUNTER_PATTERN = re.compile(r"(<!-- STB:TOTAL_START -->).+?(<!-- STB:TOTAL_END -->)", re.DOTALL)
AOTD_PATTERN    = re.compile(r"(<!-- STB:AOTD_START -->).+?(<!-- STB:AOTD_END -->)",   re.DOTALL)
STATS_PATTERN   = re.compile(r"(<!-- STB:STATS_START -->).+?(<!-- STB:STATS_END -->)", re.DOTALL)


def generate_stats_table(entries: list[dict]) -> str:
    by_letter     : dict[str, int] = defaultdict(int)
    by_category   : dict[str, int] = defaultdict(int)
    by_difficulty : dict[str, int] = defaultdict(int)

    for e in entries:
        by_letter[e["letter"]] += 1
        if e.get("category"):
            by_category[e["category"]] += 1
        if e.get("difficulty"):
            by_difficulty[e["difficulty"]] += 1

    lines = ["| Letter | Count |\n|--------|-------|\n"]
    for letter in sorted(by_letter):
        lines.append(f"| {letter} | {by_letter[letter]} |\n")

    lines.append("\n| Category | Count |\n|----------|-------|\n")
    for cat, count in sorted(by_category.items(), key=lambda x: -x[1]):
        lines.append(f"| {cat} | {count} |\n")

    lines.append("\n| Difficulty | Count |\n|------------|-------|\n")
    for diff in ["Base", "Intermediate", "Advanced"]:
        lines.append(f"| {diff} | {by_difficulty.get(diff, 0)} |\n")

    return "".join(lines)


def update_readme(entries: list[dict], aotd: dict) -> None:
    if not README_PATH.exists():
        print("  ⚠  README.md not found — skipping.")
        return

    content = README_PATH.read_text(encoding="utf-8")
    total   = len(entries)
    today   = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    content = COUNTER_PATTERN.sub(
        f"<!-- STB:TOTAL_START -->\n**{total} acronyms** — last updated {today}\n<!-- STB:TOTAL_END -->",
        content,
    )

    if aotd:
        content = AOTD_PATTERN.sub(
            f"<!-- STB:AOTD_START -->\n"
            f"### 📖 Acronym of the Day — {today}\n\n"
            f"**{aotd['acronym']}** — {aotd.get('full_name', '')}\n\n"
            f"> {aotd.get('description', '')}\n\n"
            f"*Difficulty: {aotd.get('difficulty', 'N/A')} · Category: {aotd.get('category', 'N/A')}*\n"
            f"<!-- STB:AOTD_END -->",
            content,
        )

    content = STATS_PATTERN.sub(
        f"<!-- STB:STATS_START -->\n{generate_stats_table(entries)}<!-- STB:STATS_END -->",
        content,
    )

    README_PATH.write_text(content, encoding="utf-8")
    print(f"  ✓ Updated README.md ({total} entries, AotD: {aotd.get('acronym', 'N/A')})")


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> int:
    print(f"\n{'─'*60}")
    print(" ShortTechBible — Build System")
    print(f"{'─'*60}\n")

    print("[1/4] Loading entries …")
    entries = load_all_entries()
    if not entries:
        print("  ✗ No entries found. Run validate.py first.")
        return 1
    print(f"  ✓ Loaded {len(entries)} entries from {ENTRIES_DIR}/")

    print("\n[2/4] Generating dist/acronyms.json …")
    generate_json(entries)

    print("\n[3/4] Generating dist/acronyms.csv …")
    generate_csv(entries)

    print("\n[4/4] Generating docs/acronyms_data.js …")
    generate_js_for_docs(entries)

    print("\n[4/4] Updating README.md …")
    aotd = get_acronym_of_the_day(entries)
    update_readme(entries, aotd)

    print(f"\n{'─'*60}")
    print(f" ✅  Build complete. {len(entries)} entries processed.")
    print(f"{'─'*60}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
