#!/usr/bin/env python3
"""
build.py — ShortTechBible build system
- Parses all entries/*.md
- Generates dist/acronyms.json and dist/acronyms.csv
- Generates dist/ShortTechBible.pdf via Pandoc (requires pandoc + pdflatex/xelatex)
- Updates README.md counters and Acronym of the Day section
- Generates docs/acronyms_data.js for the GitHub Pages search interface
"""

import re
import sys
import os
import json
import csv
import subprocess
import shutil
from pathlib import Path
from datetime import datetime, timezone
from collections import defaultdict

# ── Paths ────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent.parent
ENTRIES_DIR = ROOT / "entries"
DIST_DIR = ROOT / "dist"
DOCS_DIR = ROOT / "docs"
README_PATH = ROOT / "README.md"
TEMPLATE_PATH = ROOT / "pandoc-template.latex"
COMBINED_MD = DIST_DIR / "_combined.md"
OUTPUT_PDF = DIST_DIR / "ShortTechBible.pdf"
OUTPUT_JSON = DIST_DIR / "acronyms.json"
OUTPUT_CSV = DIST_DIR / "acronyms.csv"
OUTPUT_JS = DOCS_DIR / "acronyms_data.js"

# ── Parsing (shared logic with validate.py) ───────────────────────────────────

ENTRY_SEPARATOR = re.compile(r"^---\s*$", re.MULTILINE)
HEADER_RE = re.compile(r"^## ([A-Z0-9]+)(?:\s+—\s+(.+))?$")
DIFFICULTY_RE = re.compile(r"^\*\*Difficulty:\*\*\s+(.+)$")
CATEGORY_RE = re.compile(r"^\*\*Category:\*\*\s+(.+)$")


def parse_entries_from_file(filepath: Path) -> list[dict]:
    text = filepath.read_text(encoding="utf-8")
    raw_blocks = ENTRY_SEPARATOR.split(text)
    entries = []

    for block in raw_blocks:
        lines = block.strip().splitlines()
        if not lines:
            continue

        entry = {
            "acronym": None,
            "full_name": None,
            "description": "",
            "difficulty": None,
            "category": None,
            "letter": filepath.stem.upper(),
        }

        i = 0
        while i < len(lines) and not lines[i].strip():
            i += 1

        if i < len(lines):
            m = HEADER_RE.match(lines[i].strip())
            if m:
                entry["acronym"] = m.group(1)
                entry["full_name"] = m.group(2) or ""
            i += 1

        if entry["acronym"] is None:
            continue

        desc_lines = []
        in_desc = True
        while i < len(lines):
            stripped = lines[i].strip()
            dm = DIFFICULTY_RE.match(stripped)
            cm = CATEGORY_RE.match(stripped)
            if dm:
                entry["difficulty"] = dm.group(1).strip()
                in_desc = False
            elif cm:
                entry["category"] = cm.group(1).strip()
                in_desc = False
            elif in_desc and stripped:
                desc_lines.append(stripped)
            i += 1

        entry["description"] = " ".join(desc_lines)
        entries.append(entry)

    return entries


def load_all_entries() -> list[dict]:
    all_entries = []
    for md_file in sorted(ENTRIES_DIR.glob("*.md")):
        entries = parse_entries_from_file(md_file)
        all_entries.extend(entries)
    return all_entries


# ── Acronym of the Day ────────────────────────────────────────────────────────

def get_acronym_of_the_day(entries: list[dict]) -> dict:
    """Deterministic selection based on day of year, cycles through all entries."""
    if not entries:
        return {}
    day_of_year = datetime.now(timezone.utc).timetuple().tm_yday
    index = day_of_year % len(entries)
    return entries[index]


# ── Dist generation ───────────────────────────────────────────────────────────

def generate_json(entries: list[dict]) -> None:
    DIST_DIR.mkdir(exist_ok=True)
    data = {
        "meta": {
            "total": len(entries),
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source": "https://github.com/YOUR_USERNAME/ShortTechBible",
        },
        "entries": entries,
    }
    OUTPUT_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  ✓ Generated {OUTPUT_JSON.relative_to(ROOT)}")


def generate_csv(entries: list[dict]) -> None:
    DIST_DIR.mkdir(exist_ok=True)
    fieldnames = ["acronym", "full_name", "description", "difficulty", "category", "letter"]
    with OUTPUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(entries)
    print(f"  ✓ Generated {OUTPUT_CSV.relative_to(ROOT)}")


def generate_js_for_docs(entries: list[dict]) -> None:
    """Write a JS file that the GitHub Pages site imports directly (no CORS issues)."""
    DOCS_DIR.mkdir(exist_ok=True)
    js_data = json.dumps(entries, ensure_ascii=False, indent=2)
    js_content = f"// Auto-generated by build.py — do not edit manually\nconst ACRONYMS_DATA = {js_data};\n"
    OUTPUT_JS.write_text(js_content, encoding="utf-8")
    print(f"  ✓ Generated {OUTPUT_JS.relative_to(ROOT)}")


# ── Combined Markdown for Pandoc ──────────────────────────────────────────────

COVER_TEMPLATE = """\
---
title: "ShortTechBible"
subtitle: "The Open-Source IT Acronym Encyclopedia"
author: "Community Contributors"
date: "{date}"
---

"""

def generate_combined_markdown(entries: list[dict]) -> None:
    """Produce a single Markdown file ordered A–Z for Pandoc input."""
    DIST_DIR.mkdir(exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")

    by_letter: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        by_letter[e["letter"]].append(e)

    lines = [COVER_TEMPLATE.format(date=today)]

    for letter in sorted(by_letter.keys()):
        lines.append(f"# {letter}\n\n")
        for e in by_letter[letter]:
            header = f"## {e['acronym']}"
            if e.get("full_name"):
                header += f" — {e['full_name']}"
            lines.append(f"{header}\n\n")
            if e.get("description"):
                lines.append(f"{e['description']}\n\n")
            if e.get("difficulty"):
                lines.append(f"**Difficulty:** {e['difficulty']}  \n")
            if e.get("category"):
                lines.append(f"**Category:** {e['category']}\n\n")
            lines.append("---\n\n")

    COMBINED_MD.write_text("".join(lines), encoding="utf-8")
    print(f"  ✓ Generated {COMBINED_MD.relative_to(ROOT)}")


# ── PDF via Pandoc ────────────────────────────────────────────────────────────

def build_pdf() -> bool:
    if not shutil.which("pandoc"):
        print("  ⚠  pandoc not found in PATH — skipping PDF generation.")
        print("     Install with: sudo apt install pandoc texlive-xetex")
        return False

    cmd = [
        "pandoc",
        str(COMBINED_MD),
        "--output", str(OUTPUT_PDF),
        "--pdf-engine=xelatex",
        "--toc",
        "--toc-depth=1",
        "--number-sections",
        "--highlight-style=tango",
        "-V", "geometry:margin=1in",
        "-V", "fontsize=11pt",
        "-V", "colorlinks=true",
        "-V", "linkcolor=NavyBlue",
        "-V", "toccolor=NavyBlue",
        "-V", "urlcolor=NavyBlue",
        "-V", "mainfont=DejaVu Serif",
        "-V", "monofont=DejaVu Sans Mono",
    ]

    if TEMPLATE_PATH.exists():
        cmd += ["--template", str(TEMPLATE_PATH)]

    print(f"  ⚙  Running pandoc to generate PDF …")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"  ✗ Pandoc failed:\n{result.stderr}")
        return False

    print(f"  ✓ Generated {OUTPUT_PDF.relative_to(ROOT)}")
    return True


# ── README update ─────────────────────────────────────────────────────────────

COUNTER_PATTERN = re.compile(
    r"(<!-- STB:TOTAL_START -->).+?(<!-- STB:TOTAL_END -->)", re.DOTALL
)
AOTD_PATTERN = re.compile(
    r"(<!-- STB:AOTD_START -->).+?(<!-- STB:AOTD_END -->)", re.DOTALL
)
STATS_PATTERN = re.compile(
    r"(<!-- STB:STATS_START -->).+?(<!-- STB:STATS_END -->)", re.DOTALL
)


def generate_stats_table(entries: list[dict]) -> str:
    by_letter: dict[str, int] = defaultdict(int)
    by_category: dict[str, int] = defaultdict(int)
    by_difficulty: dict[str, int] = defaultdict(int)

    for e in entries:
        by_letter[e["letter"]] += 1
        if e.get("category"):
            by_category[e["category"]] += 1
        if e.get("difficulty"):
            by_difficulty[e["difficulty"]] += 1

    lines = ["| Letter | Count |\n|--------|-------|\n"]
    for letter in sorted(by_letter):
        lines.append(f"| {letter} | {by_letter[letter]} |\n")

    lines.append("\n| Category | Count |\n|----------|-------|\n")
    for cat, count in sorted(by_category.items(), key=lambda x: -x[1]):
        lines.append(f"| {cat} | {count} |\n")

    lines.append("\n| Difficulty | Count |\n|------------|-------|\n")
    for diff in ["Base", "Intermediate", "Advanced"]:
        lines.append(f"| {diff} | {by_difficulty.get(diff, 0)} |\n")

    return "".join(lines)


def update_readme(entries: list[dict], aotd: dict) -> None:
    if not README_PATH.exists():
        print("  ⚠  README.md not found — skipping README update.")
        return

    content = README_PATH.read_text(encoding="utf-8")
    total = len(entries)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Update total counter
    new_total_block = (
        f"<!-- STB:TOTAL_START -->\n"
        f"**{total} acronyms** — last updated {today}\n"
        f"<!-- STB:TOTAL_END -->"
    )
    content = COUNTER_PATTERN.sub(new_total_block, content)

    # Update Acronym of the Day
    if aotd:
        aotd_text = (
            f"<!-- STB:AOTD_START -->\n"
            f"### 📖 Acronym of the Day — {today}\n\n"
            f"**{aotd['acronym']}** — {aotd.get('full_name', '')}\n\n"
            f"> {aotd.get('description', '')}\n\n"
            f"*Difficulty: {aotd.get('difficulty', 'N/A')} · "
            f"Category: {aotd.get('category', 'N/A')}*\n"
            f"<!-- STB:AOTD_END -->"
        )
        content = AOTD_PATTERN.sub(aotd_text, content)

    # Update stats table
    stats_block = (
        f"<!-- STB:STATS_START -->\n"
        f"{generate_stats_table(entries)}"
        f"<!-- STB:STATS_END -->"
    )
    content = STATS_PATTERN.sub(stats_block, content)

    README_PATH.write_text(content, encoding="utf-8")
    print(f"  ✓ Updated README.md ({total} entries, AotD: {aotd.get('acronym', 'N/A')})")


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> int:
    print(f"\n{'─'*60}")
    print(" ShortTechBible — Build System")
    print(f"{'─'*60}\n")

    # 1. Load all entries
    print("[1/6] Loading entries …")
    entries = load_all_entries()
    if not entries:
        print("  ✗ No entries found. Run validate.py first.")
        return 1
    print(f"  ✓ Loaded {len(entries)} entries from {ENTRIES_DIR}/")

    # 2. Generate JSON
    print("\n[2/6] Generating dist/acronyms.json …")
    generate_json(entries)

    # 3. Generate CSV
    print("\n[3/6] Generating dist/acronyms.csv …")
    generate_csv(entries)

    # 4. Generate JS for GitHub Pages
    print("\n[4/6] Generating docs/acronyms_data.js …")
    generate_js_for_docs(entries)

    # 5. Generate PDF
    print("\n[5/6] Generating PDF …")
    generate_combined_markdown(entries)
    build_pdf()

    # 6. Update README
    print("\n[6/6] Updating README.md …")
    aotd = get_acronym_of_the_day(entries)
    update_readme(entries, aotd)

    print(f"\n{'─'*60}")
    print(f" ✅  Build complete. {len(entries)} entries processed.")
    print(f"{'─'*60}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
